tests/2015-08/07-multi-hop/task03.py

Basic multi hop testing with RPL on the iotlab testbed. Still WIP

[WIP] 2015.08: multi-hop test on iotlab testbed

---

05-single-hop-route/05-single-hop-route.md

Replaces `fibroute` command in task 5 with `nib route` command.

task-05: update helper description for NIB

---

04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md
05-single-hop-route/05-single-hop-route.md
06-single-hop-udp/06-single-hop-udp.md
07-multi-hop/07-multi-hop.md

I found some leaks in the packet buffer for certain conditions in
fragmentation. While not fixed in master at the writing of this change
in RIOT's master, this serves as a reminder that that should be
checked.

6Lo tests: also check for pktbuf leaks

---

07-multi-hop/IOTLABHelper.py
07-multi-hop/task01.py
07-multi-hop/task02.py

This fixes issues I got when running 07-multi-hop for the last release
My main concern is that `ifconfig` does not print the `/PREFIX` on addresses and I do not know if it is really a wanted thing or not. However it is required for running the tests.
* Update to `nib` shell commands
* Fix nodes not being sorted as `sorted` does not sort in place
* Update to the new `ifconfig` API
And some cleanups
* Update to an unicode pexpect (I think I got decode error but not sure anymore)
* Update to new iotlab- commands to not get deprecation warnings
* Whitespace
Referenced in:
https://github.com/RIOT-OS/Release-Specs/issues/62#issuecomment-388376218

07-multi-hop: Fix issues found when doing Release 2018.04

---

01-ci/task01.py
01-ci/task02.py
01-ci/task03.py
01-ci/task04.py

Changes are:
* Use python3
* Print execution output
* Remove execution timeout, (I replaced by `subprocess` for some executions).
* use `make test` when possible
* Use `spawnu` for unicode
I had trouble running the tests for 01-ci due to the timeouts.
I took some time to update the scripts to python3 and using make test.

01-ci: update scripts

---

08-interop/08-interop.md

The issue was fixed in lwIP and with [this change][1] the fix is also available in RIOT.
Requires https://github.com/RIOT-OS/RIOT/pull/10059 to be merged.
[1]: https://github.com/RIOT-OS/RIOT#10059

task8: re-include lwIP into interop tests

---

.gitignore
02-tests/02-tests.md
02-tests/compile_and_test_for_board.py
09-compile-and-test-one-board/09-compile-and-test-one-board.md

Add a script to compile and execute test on a board and produce file results.
I want to add a new release spec step where board maintainers run tests on their own board, with their normal working setup and give us the compilation/tests results.
I do not call it a "test" as I do not want it blocking for a release, but more as a goal of gathering information on the current state of board support and test suite.
TODO:
* Should be ok
This adds a script that goes into all applications and, if the board is supported, calls `make clean all`, and then `make flash test` if there are tests.
It produces results in `results/board/tests/name/` with `compilation.success` or `.failed` and `test.success` or `test.failed`. The goal was to produce file results with the execution trace on failure. I also …

09-compile-and-test-one-board: add script to test board

---

06-single-hop-udp/06-single-hop-udp.md

Just noticed this while scanning over the currently ongoing tests: 61616 is not just "another port". It's within the port range of compressible ports for [6LoWPAN's UDP NHC][RFC6282].
[RFC6282]: https://tools.ietf.org/html/rfc6282#section-4.3.1

task06: clarify port choice for 6.2

---

04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md

The title of 4.8 is misleading, as the test doesn't run for 15 min.

task4: change misleading title

---

02-tests/compile_and_test_for_board.py

Allow overwriting compile 'clean all' and 'test' commands.
This will allow running for example 'scan-build-analyze' for building
and also other test commands like 'robottest', 'pytest',
'archive-check' as currently exist in some PRs.
It still currently hardwritten how to finding if there is a test
as it is not integrated in RIOT or if a board is supported for the
application.
It also required the two first commits to move PARSER at the end and print the default value in help messages to make in understandable by users what goes in '--compile-targets'.
Overwrite the compile command with for example `distclean all`.
```
./compile_and_test_for_board.py --applications="tests/bloom_bytes" --compile-targets="distclean all"  --loglevel=debug ~/work/git/RIOT native
INFO:native:Saving toolchain …
```

02-tests:compile_and_test_for_board: allow setting 'all' and 'test'

---

10-icmpv6-error/10-icmpv6-error.md

This just adds the test descriptions for testing ICMPv6 error message behavior. The tests are based on the testing procedures I proposed for https://github.com/RIOT-OS/RIOT/pull/8594, but re-ordered to reflect the order they have in [RFC 4443](https://tools.ietf.org/html/rfc4443) and not for incremental configuration as it was in https://github.com/RIOT-OS/RIOT/pull/8594. I will provide a test script soon as a separate PR, based on #79 and the test scripts I provided in https://github.com/RIOT-OS/RIOT/pull/8594.

10-icmpv6-error: Add ICMPv6 error message release specs

---

04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md

This test is aiming to detect regressions to https://github.com/RIOT-OS/RIOT/issues/10672 and https://github.com/RIOT-OS/RIOT/issues/10701.

task04: add ICMPv6 stress test

---

09-coap/coap.md
09-coap/setup_tap.sh
09-coap/task03.py
09-coap/task04.py
09-coap/task05.py
09-coap/teardown_tap.sh

Basic coverage for CoAP messaging as described in #73. The goal for this PR is to include non-confirmable and confirmable messaging, block extension, and observe extension. Includes some tests for both gcoap and nanocoap. Includes test of RIOT Resource Directory client implementation (CORD).
Initial commit probably premature, but I wanted to get the message out that I'm working on it for the 2018.10 release. :-)
Resolves #73

09-coap: add CoAP release specs

---

06-single-hop-udp/06-single-hop-udp.md

Adds a regression test for the bug fixed in https://github.com/RIOT-OS/RIOT/pull/10860 (and as an extra also the same kind of test for 6Lo-based nodes).

task06: add specification for neighbor address resolution errors

---

06-single-hop-udp/06-single-hop-udp.md

This removes the `channel` configuration for the single hop UDP test on native, which is not applicable.

06-single-hop-udp: Remove channel for native

---

10-icmpv6-error/10-icmpv6-error.md

Since the MTU field of a Packet Too Big message is quite important for Path MTU Discovery (see [RFC 8201](https://tools.ietf.org/html/rfc8201)) we should check its value in our release tests.

task10: add requirement for MTU field of Packet Too Big message

---

03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md
04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md

Intended to check if there is a regression to https://github.com/RIOT-OS/RIOT/pull/6123.
**Do not merge until https://github.com/RIOT-OS/RIOT/pull/6123 is closed!** (current fix proposal in https://github.com/RIOT-OS/RIOT/pull/10891).

task03: add stress test for native

---

10-icmpv6-error/10-icmpv6-error.md

When fixing the interfaces in https://github.com/RIOT-OS/Release-Specs/pull/93 I accidentally changed them for the wrong task. Task 4 is compiled normally, so the application doesn't have any additional interfaces or a 6Lo thread. Task 7 is compiled with `socket_zep` included, so its interface identifiers are different.

task10: fix interface switch up

---

10-icmpv6-error/10-icmpv6-error.md

Found another bug in the test description for task 10: `sendp()` has no `timeout` argument

task10: fix scapy send command

---

03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md

This adds another stress test for ICMPv6 to reflect the findings in the ongoing 2019.01-RC3 testings.
**Do not merge, until the issues found in ~~2019.01-RC3~~ 2019.01-RC2 are not fixed in RIOT**

task03: add additional stress test

---

07-multi-hop/IOTLABHelper.py
07-multi-hop/example_test_guide.md

With https://github.com/RIOT-OS/RIOT/pull/9523 the syntax of `ping6` slightly changed. This fixes all occurrences of this in this Repo so far.
**do not merge before testing for 2019.01 is finished** (this only affects 2019.04).

Adapt for new ping6 command

---

11-lorawan/11-lorawan.md

This fixes a typo in the lorawan release specs that I found while checking them in #105

lorawan: fix typo in persistence task

---

06-single-hop-udp/06-single-hop-udp.md

Since https://github.com/RIOT-OS/RIOT/issues/11163 is fixed now, let's ensure that there won't be a regression to that.

task06: add specifications for empty packets

---

04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md

Due to fragmentation the average round trip time of a link-local ping
is about 140ms (depending on distance). This puts a strain on both
packet buffer and reassembly buffer on the sending nodes as it has to
handle at least two packets while it is also working on a reply.
Add to that that the `at86rf2xx` driver is only able to send when it is
not in receive state (and blocks until it leaves) the pinged node has
problems to get out the data it wants to send the echo replies while it
is being spammed with fragments containing follow-up echo requests.
Because the test is mainly about testing fragmentation, not
fragmentation under stress, I suggest we tweak the test parameters a
bit so the test takes the same time, but with less stress on the node.
Also see …

task04: change timings for large payload test

---

05-single-hop-route/05-single-hop-route.md

Due to fragmentation the average round trip time of a link-local ping
is about 140ms (depending on distance). This puts a strain on both
packet buffer and reassembly buffer on the sending nodes as it has to
handle at least two packets while it is also working on a reply.
Add to that that the `at86rf2xx` driver is only able to send when it is
not in receive state (and blocks until it leaves) the pinged node has
problems to get out the data it wants to send the echo replies while it
is being spammed with fragments containing follow-up echo requests.
This test is about being able to route packets without packet loss, not
whether this process can happen under stress. Therefore there is no
penalty in relaxing the timings as much as necessary, apart from a
longer test time.

task05: increase timing for large payload tests

---

08-interop/08-interop.md

This provides the testing procedures for task 8.3. It also adapts the specifications to the tests that actually happened in the past (UDP exchange, not ICMPv6 echo request/reply as the latter are much harder to realize with contiki)

task08.3: add testing procedures

---

07-multi-hop/example_test_guide.md

This is more of an RFC. I think the second ping command is redundant, since the ping exchange is already bidirectional (so compared to UDP we don't have to check "the other direction"). However, I see the benefit in having a redundant ping from the other end to mitigate errors in the setup.

task07: remove redundant ping

---

04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md
04-single-hop-6lowpan-icmp/example_test_guide.md

Since the ping6 is now async some parameters must be updated so it doesn't stumble on itself.
Also a guide is added so people who cannot read minds can mindlessly follow and test.

spec/04: Update the 04-single-hop-6lowpan-icmp specs

---

02-tests/02-tests.md

This prevents the test engineer from running the tests and then
realising that the test requires the tap bridge to be up.
Reopen of #125.

02-tests: Specify that tapsetup should be run first

---

07-multi-hop/example_test_guide.md

While working on #138 I noticed, that the example guide for task 7 says to send "a packet", while the command provided with that instruction sends 100 packets.

task07: fix wording in example guide

---

03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md
04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md
04-single-hop-6lowpan-icmp/example_test_guide.md
07-multi-hop/07-multi-hop.md
07-multi-hop/example_test_guide.md

See https://github.com/RIOT-OS/Release-Specs/issues/137
Requires https://github.com/RIOT-OS/RIOT/pull/12375 for simple deployment

task0{3,4,7}: Add tests for IPv6 fragmentation

---

04-single-hop-6lowpan-icmp/example_test_guide.md

During a stress test having high packet loss is OK.
As long as it can recover it should be fine.
The criteria was incorrect.

spec04/task09: Update example guide pass criteria

---

10-icmpv6-error/10-icmpv6-error.md

Addresses the upstream fix in https://github.com/RIOT-OS/RIOT/pull/12522

spec10/task07: activate SLAAC

---

04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md

This PR does two things:
- homologate examples_test_guide.md and specs
- change payload to work with default 9600 xbee baudrate
I changed the payload since form what I was able to test in 2020.01 and 2019.10 `xbee` can't handle100b payload at 100ms interval.
- Run the old spec on 2020.01 and 2019.10
- Run the new spec on 2020.01 and 2019.10

04-single-hop-6lowpan-icmp: change task08 interval to 350ms

---

11-lorawan/11-lorawan.md

This just fixes the numeration of the last LoRaWAN task, as it was duplicated.

11-lorawan: Fix task numeration

---

08-interop/08-interop.md
README.md
REPLACED.md

`emb6` was deprecated in https://github.com/RIOT-OS/RIOT/pull/12389 and removed in https://github.com/RIOT-OS/RIOT/pull/14494 so it does not make much sense to test this anymore, even for 2020.07
Resolves #141

08-interop: deprecate 9-10

---

.github/workflows/self-test.yml
.gitignore
README.md
conftest.py
setup.cfg
testutils/.coveragerc
testutils/asyncio.py
testutils/iotlab.py
testutils/native.py
testutils/pytest.py
testutils/shell.py
testutils/tests/__init__.py
testutils/tests/test_iotlab.py
testutils/tests/test_native.py
testutils/tests/test_pytest.py
testutils/tests/test_shell.py
tox.ini

Third time's a charm: after https://github.com/RIOT-OS/Release-Specs/pull/79 and some major overhaul of that framework to use (then) `riotnode` (now `riotctrl`) and `pytest` by @fjmolinas, I ported the latter to run with the new [`riotctrl`](https://github.com/RIOT-OS/riotctrl/) python package and the in-tree [`riotctrl_shell`](https://github.com/RIOT-OS/RIOT/tree/b05b2fddb967b170f2c2cdcfda5641085d55fbcc/dist/pythonlibs/riotctrl_shell) module.
I also cleaned up the by now very complicated history of that effort and squashed a lot of commits. Since the most of the porting work was done by @fjmolinas (I just moved some code around and enhanced his code) I made him the main author of the work in the commit history, but added all co-authors to the respective commits for the changes they made. …

testutils: Automated testing environment for release tests using pytest

---

04-single-hop-6lowpan-icmp/test_spec04.py

Taken out of the original #155, this provides automated tests (where possible with the current framework) for spec 4 to the new, pytest-based framework.
Requires #155

 04-single-hop-6lowpan-icmp: initial import of automated tests

---

conftest.py

While debugging a problem using the new framework I noticed, that it can be really annoying, when the flash fails and the test just runs with the old image ;-).
This makes a test fail if the `make flash` fails for some reason (e.g. build error) by using the `check=True` parameter. Likewise, it makes piping the output to `DEVNULL` optional (bound to `--hide-output`), to debug potential problems during the build. Lastly, it now uses the `DEVNULL` of `subprocess` instead of the self-defined one.

pytest: fail test on flash fail

---

05-single-hop-route/test_spec05.py

Taken out of the original #155, this provides automated tests (where possible with the current framework) for spec 5 to the new, pytest-based framework.
Requires #155

05-single-hop-route: initial import of automated tests

---

03-single-hop-ipv6-icmp/test_spec03.py

Taken out of the original #155, this provides automated tests (where possible with the current framework) for spec 3 to the new, pytest-based framework.
Requires #155

03-single-hop-ipv6-icmp: initial import of automated tests

---

06-single-hop-udp/test_spec06.py

Taken out of the original #155, this provides automated tests (where possible with the current framework) for spec 6 to the new, pytest-based framework.
Requires #155

06-single-hop-udp: initial import of automated tests

---

08-interop/test_spec08.py

This provides automated tests (where possible with the current framework) for spec 8 to the new, `pytest`-based framework.
Requires #155

08-interop: initial import of automated tests

---

10-icmpv6-error/test_spec10.py
conftest.py

This provides automated tests (where possible with the current framework) for spec 10 to the new, pytest-based framework.
Requires #155 and https://github.com/RIOT-OS/RIOT/pull/14510

10-icmpv6-error: initial import of automated tests

---

setup.cfg
tox.ini

This takes out the remaining commit in #164, so that `pylint` and `flake8` are always executed on all tests.
For testing, just look at the output of the github action in the status of this PR. `pylint` and `flake8` should now be executed

tox: activate flake8 and pylint on default runs

---

03-single-hop-ipv6-icmp/test_spec03.py

I was wondering why some `native` tests are failing with high losses and many tests of spec 10 were failing outright. So I [used `scapy`'s sniffer in the spec 10 tests](https://github.com/RIOT-OS/Release-Specs/commit/d1dde5bbf8b3de065790ef708639bd54b753d9de) and [upload the PCAP generated by that](https://github.com/miri64/RIOT/commit/f11ea24341314f3cee7525163477dcbd67741b5f#diff-64da09ece1cfe234928d5e51cfca3e09R104) to get a better picture what is going wrong. It turns out, there are a lot of ICMPv6 echo requests on the TAP interface. This can be seen in the PCAPs artifacts of [this run](https://github.com/miri64/RIOT/actions/runs/187260182). Turns out: Some of the force-`ping`s in task 3.4 where not finished properly (even though they do locally).
By sending a `SIGINT` (= Ctrl+C) to the …

03-single-hop-ipv6-icmp/task04: stop pingers after force-ping

---

04-single-hop-6lowpan-icmp/test_spec04.py

The lazy version for "fixing" 4.4 if we can not resolve https://github.com/RIOT-OS/Release-Specs/pull/181#issuecomment-667517820.

04-single-hop-6lowpan-icmp/task04: xfail pktbuf on pinged node

---

README.md
conftest.py
testutils/pytest.py

Sometimes you need a clean, direct log from the nodes and not whatever filtered stuff comes out of `pexpect`. This provides the capability to do that with the pytest framework for the release tests.
Requires https://github.com/RIOT-OS/RIOT/pull/14664 to actually work.

pytest: add capability to log nodes to file

---

08-interop/README.md

Add a specification for testing the WiFi uplink with an esp*.
This also allows us to test routing to the wider internet (via border router) and DNS operation.
Requirement is a IPv6 uplink and a router that allows enabling prefix delegation (IA_PD) via DHCPv6.
Fixes #150

08-interop: add test for WiFi <-> DHCPv6 router 

---

09-coap/test_spec09.py

I found a typo in task 9.1 while reviewing and testing #190. This never made any problems so far, since the `examples/cord_ep` application is configured as expected and more of a fail-safe than anything else.

09-coap/task01: fix typo

---

10-icmpv6-error/README.md
10-icmpv6-error/test_spec10.py

With https://github.com/RIOT-OS/RIOT/pull/15430 in current master of RIOT, both `socket_zep` and `native_tap` needs to be added to `USEMODULE` if both devices want to be used. Otherwise, [only one of both will be selected](https://github.com/RIOT-OS/RIOT/runs/1502334614?check_suite_focus=true#step:9:72). This PR updates the doc and the test of task 10.7 to reflect that change.
To test, just run
```sh
sudo RIOTBASE=$(readlink -f <riotpath>) tox -- -k "spec10 and task07" --non-RC
```
with `<riotpath>` having a current version of RIOT master checked out. Without this PR, the test will fail, with it, it will succeed.

10-icmpv6-error: fix task07 for RIOT-OS/RIOT#15430

---

08-interop/README.md

`gnrc_ipv6_nib_dns` was split off `sock_dns`, but we need both for name resolution.

08-interop: gnrc_ipv6_nib_dns is required to have name resolution in the WPAN

---

04-single-hop-6lowpan-icmp/README.md
04-single-hop-6lowpan-icmp/test_spec04.py
conftest.py

~This PR removes the experimental tag of tasks 05 and 06 (between samr21-xpro and remote-revb), since the remote-revb compiles by default to the Radio HAL variant. Therefore it should be covered.~
This PR:
- Adds duplicates of tasks 05, 06 and 09 to be ran with the nrf52840dk. This is required since the `nrf52840dk` uses by default `netdev_ieee802154_submac`, which runs the IEEE 802.15.4 Radio HAL implementation.
- Removes the experimental tag of tasks 05 and 06 (between samr21-xpro and remote-revb), since the remote-revb compiles by default to the Radio HAL variant. Therefore it should be covered. I also expanded the test to other CC2538 radios (e.g Firefly), since they are available on IoT-LAB
- Adds a fixture for configuring the IoT-LAB site on a per-tasks basis.
I also updated the …

04-single-hop: increase radio HAL coverage

---

11-lorawan/README.md

This commit adds some GNRC LoRaWAN tests. These tests cover the
different join procedures (OTAA and ABP), sending confirmed and
unconfirmed messages and receiving downlinks from the Network
Server.
Check that the tests make sense

11-lorawan: add GNRC LoRaWAN tests

---

.github/workflows/self-test.yml

@aabadie warned me to use that plugin, and now it shows... for some reason it does not execute neither flake8 nor pylint. This removes the usage of the `tex-gh-actions` plugin and also adds `3.9` tests.

gh-actions: don't use tox-gh-actions plugin

---

04-single-hop-6lowpan-icmp/test_spec04.py

This PR adds some missing `@iotlab_creds` decorators to tasks 12 and 13. Without these, the release-tests won't pick them.

04-single-hop-6lowpan-icmp: add missing iotlab_creds

---

README.md

The link to `REPLACED.md` introduced in https://github.com/RIOT-OS/Release-Specs/pull/157 is not a link, as the reference documentation is missing. This adds it ;-)

README.md: fix link to REPLACED.md

---

07-multi-hop/example_test_guide.md

- The default interface is 5 now
- The packet buffer check command is `pktbuf`
- There is a separate build command from the flash and term (because concurrency issues)
- A step to initialize the `rpl` instance is added for all nodes
- The experimental has the current state of the results

task7: update example_test_guide

---

03-single-hop-ipv6-icmp/test_spec03.py
04-single-hop-6lowpan-icmp/test_spec04.py
05-single-hop-route/test_spec05.py
06-single-hop-udp/test_spec06.py
07-multi-hop/test_spec07.py
testutils/shell.py
testutils/tests/test_shell.py

This commit fixes some race conditions when checking that all pinged nodes
have an empty pktbuf. This PR adds an utility to wait for some seconds before probing the pktbuf status.
Without this commit some of these tests fail randomly (e.g see https://github.com/RIOT-OS/RIOT/actions/runs/537422117)
```
RIOTBASE=<absolute_path_to_RIOT_folder> IOTLAB_SITE=grenoble tox -- --non-RC -k "spec04"
```
I'm explicitly choosing a different IoTLAB site because on 8/2/2021 all Saclay nodes are reserved.

testutils/shell: add check_pktbuf

---

99-compile-and-test-one-board/README.md

We have the technology, so let's link the spec `99-compile-and-test-one-board` is referring to.

99-compile-and-test-one-board: add link for 02-tests

---

08-interop/test_spec08.py

Due to RIOT-OS/RIOT#15992 the parsing in [the release tests](https://github.com/RIOT-OS/RIOT/runs/1993539557) currently fails. Where
```sh
$ RIOTBASE=$(readlink -f ../RIOT) tox -- --non-RC -k "spec08 and task08"
```
failed before, it should succeed with this PR. (If you are facing the same problem I did that the test fails because of a `FileNotFoundError`: that's [a bug in python 3.9](https://bbs.archlinux.org/viewtopic.php?id=261816). Just delete `10-icmpv6-error/test_spec10.py` for the test (the tests in there are deselected with the command above anyways), and it will work.

task8.4: fix address parsing for RIOT-OS/RIOT#15992

---

09-coap/test_spec09.py
11-lorawan/test_spec11.py
conftest.py
requirements.txt
testutils/pytest.py
testutils/shell.py
testutils/tests/test_github.py
testutils/tests/test_pytest.py
testutils/tests/test_shell.py
testutils/tests/test_ttn.py
testutils/ttn.py
tox.ini

Duplicate of #201 , but this time from the right repo...
This PR adds the RIOTCtrl counterpart for #199. This test is using a TTN account and MQTT in order to check uplink and downlink messages, besides activations from the Network Server.
I plan to migrate the existing semtech LoRaMAC tests as soon as possible in order to also use these mechanisms, but I gave priority to GNRC LoRaWAN because it had no autotests.
Check github workflow output
#199

11-lorawan: add RIOTCtrl tests for GNRC LoRaWAN

---

04-single-hop-6lowpan-icmp/test_spec04.py
05-single-hop-route/test_spec05.py
06-single-hop-udp/test_spec06.py
07-multi-hop/test_spec07.py
08-interop/test_spec08.py
requirements.txt

Oftentimes tests fail only because there is currently a lot of noise in the IoT-LAB testbed due to ongoing experimentation (as it is currently the case for some of the [latest runs](https://github.com/RIOT-OS/RIOT/actions/workflows/release-test.yml). This change allows for those tests to be repeated on failure after 30 seconds up to 3 times.
Experimental tests marked with XFAIL are skipped for this as they will be marked as skipped on failure anyway and that should not be hidden.

release-tests: mark IoT-LAB runs as flaky

---

conftest.py

Whenever scrolling through the `release-tests` log, I waste a lot of time scrolling through the build log which in most cases is not really interesting. Now that `QUIETER` was introduced in https://github.com/RIOT-OS/RIOT/pull/16513 we can use that to prevent that. If for any reason, we want to check the modules used, we still can use `make info-modules` (which would have the added benefit that it also lists pseudo-modules).

pytest: make builds quieter

---

11-lorawan/test_spec11.py

This PR adds a pktbuf check at the end of each GNRC LoRaWAN test. This will help detecting issues such as https://github.com/RIOT-OS/RIOT/pull/16584
Run 11-lorawan and makes sure the tests passes or fails (on current master). It shouldn't report "ERROR".

11-lorawan: add pktbuf check

---

requirements.txt
testutils/github.py
testutils/tests/test_github.py

This makes Murdock less spammy in the release candidate test tracking issues.
See ~~https://github.com/RIOT-OS/Release-Specs/issues/227#issuecomment-874236990~~ https://github.com/RIOT-OS/Release-Specs/issues/227#issuecomment-874717209 for a currently generated example comment.

testutils.github: use sticky comments

---

.devdata.env.sample
.gitignore
README.md
tox.ini

Some tests require an extended list of environment variables (e.g LoRaWAN tests).
This PR adds https://github.com/seanh/tox-envfile/blob/master/tox_envfile.py in order to be able to store these environment variables in an env file.
Due to limitations in the original pkg, the env file is named ".devdata.env" instead of the standard ".env". Maybe we can upstream this change at some point...
Copy the sample environment file:
```sh
cp .devdata.env.sample .devdata.env
```
And set RIOTBASE accordingly. Simply calling "tox" shouldn't complain that RIOTBASE is missing.

tox-envfile: add support for env file

---

11-lorawan/test_spec11.py

Mark task06 as local only since it will work with chirpstack(some versions) but not ttn. It can be removed once https://github.com/RIOT-OS/RIOT/issues/16962 is addressed. It should keep release-tests outputs clean IMO.
I'm also pushing for this because it seems that the failing test messes with the following iterations of the LoraWAN tests (something in the TTN state for that node). I'm able to fix it by resetting the node test: e.g.: `ttn-lw-cli end-devices reset release-tests eui-70b3d57ed00463e7-otaa`, but I haven't found an mqtt interface for this. I'm not sure why this happens either, but I can't investigate this further ATM.

11-lorawan: mark task06 as local only

---

09-coap/test_spec09.py
setup.cfg
testutils/native.py
testutils/shell.py
testutils/tests/test_github.py

The address output of `examples/nanocoap_server` was changed to JSON in https://github.com/RIOT-OS/RIOT/pull/18161. This changes the parsing to account for that.
Run
```sh
sudo dist/tools/tapsetup/tapsetup
RIOTBASE=$(readlink -f ../RIOT) tox -e test -- -k "spec09 and (task03 or task04)" --non-RC
```
with current RIOT master checked out at `../RIOT`.

spec09: task03/task04: adapt for new JSON output

---

03-single-hop-ipv6-icmp/README.md
04-single-hop-6lowpan-icmp/README.md
04-single-hop-6lowpan-icmp/test_spec04.py
05-single-hop-route/README.md
05-single-hop-route/test_spec05.py
06-single-hop-udp/README.md
07-multi-hop/README.md
07-multi-hop/example_test_guide.md
11-lorawan/test_spec11.py

Replace the deprecated module gnrc_pktbuf_cmd with the new shell_cmd_gnrc_pktbuf module.
See https://github.com/RIOT-OS/RIOT/pull/18355#issuecomment-1256915237

tree-wide: s/gnrc_pktbuf_cmd/shell_cmd_gnrc_pktbuf/

---

09-coap/README.md
09-coap/test_spec09.py

The parameter for `cord_ep register` was changed in https://github.com/RIOT-OS/RIOT/pull/18053 to be a full URI, not just a server name + registration interface. This fixes the specs and tests to reflect that. /cc @Teufelchen1

09-coap: use URI with `cord_ep register`

---

08-interop/README.md

[REPLACED.md](https://github.com/RIOT-OS/Release-Specs/blob/master/REPLACED.md) lists tasks 8.09 and 8.10 as replaceable after 2021-05-01, which was nearly 1,5 years ago. So this just remove the tasks and add a comment about why.

08-interop: remove deprecated tasks

---

.devdata.env.sample
.github/workflows/self-test.yml
tox.ini

This module does not support tox >= 4 and causes an error
pluggy._manager.PluginValidationError: unknown hook 'tox_configure' in plugin
<module 'tox_envfile' from ...>
=> deactivate for now.

tox-envfile: deactivate for now

---

09-coap/test_spec09.py

This should fix
```
> coap get -c fd00:bbbb::1 5683 /time
coap get -c fd00:bbbb::1 5683 /time
usage: coap <get|post|put> [-c] <host>[:port] <path> [data]
coap ping <host>[:port]
Options
-c  Send confirmably (defaults to non-confirmable)
```

09-coap/test_spec09.py: update coap shell command use

---

conftest.py

Should fix the issue observed in https://github.com/RIOT-OS/RIOT/actions/runs/3881157262/jobs/6619863473. Should we run another round? I only tested
```sh
RIOTBASE=$(readlink -f ../RIOT) tox -e test -- -k "spec04 and task01" --non-RC
```
locally.

conftest: riot_ctrl: reset after flash on IoT-LAB

---

99-compile-and-test-one-board/README.md

See [notes from today's meeting](https://forum.riot-os.org/t/weekly-coordination-call-friday-at-10am-cet/3068/232) (only accessible for maintainers so here is the quote in question):
> martine: You are aware that the CI does on test-on-* ([RYOT](https://github.com/RIOT-OS/RIOT/actions/workflows/test-on-ryot.yml) and [IoT-LAB](https://github.com/RIOT-OS/RIOT/actions/workflows/test-on-iotlab.yml)) do run this on a few boards through CI? No… (maybe mention it in the 99-* doc?)
Apparently, not even recent release managers know about these, so at least mention them in the specs.

99-compile-and-test-one-board: add note on boards tested in CI

---

testutils/tests/test_github.py

This PR is an attempt to fix the problem raised in #283. The problem seems to come from a trailing "\n" at the end of the body content that is added by BeautifulSoup apparently. I haven't found how to prevent BeautifulSoup from doing that.
So the idea is simply to compare the stripped content of the bodies (computed vs expected).
The other option is to add `\n` to the end of each expected bodies. I can change this PR to that if it's preferred. Or maybe someone knows how to adapt the beautifulsoup code that generates the `tbody` tag.

testutils/test_github: compare stripped bodies

---

requirements.txt

With this, the release tests should run again in RIOT master.

requirements.txt: pin pytest to <7.4 for the moment

---

04-single-hop-6lowpan-icmp/README.md
04-single-hop-6lowpan-icmp/test_spec04.py
testutils/iotlab.py
testutils/shell.py

The lille site doesn't have any engineers there and all `firefly` boards are have ERROR.
As a result, tests using them are failing.  Since the tests try to use a `cc2538` radio, only `strasbourg` seems to have them, though no samr21-xpros.  So we will have to switch to `iotlab-m3` boards.

Spec04 use iotlab-m3 and openmote-b

---

08-interop/README.md
08-interop/compile_contiki.sh
08-interop/test_spec08.py
conftest.py

This is based off the work @jia200x did.
Still a WIP but here are the issues I have found so far.
- There is no easy way to setup and get the contiki binary so I added a script that can be run and re-run to do so (for local testing... still needs some cleanup)
- We can override `FLASHFILE` to use the existing `riotctrl` infrastructure but `iotlabs` actually uses `BINFILE` to speed things up... that took me a while
- Some hacks were needed in order to use the `flash-only` step maybe that could be cleaned
- Somehow the captured output seems to be a bit funny for the last ping6 command that is wrapped, maybe better to just do it manually.
<details>
```
NETOPT_TX_END_IRQ not implemented by driver
main(): This is RIOT! (Version: 2024.01-devel-11-g354e1-2023.10-branch)
RIOT network stack …
```

Automate spec08 task03 contiki interop tests

---

08-interop/compile_contiki.sh

It seems like there were some permission issues only on the github actions runners... Oops.
I guess this [solves it](https://github.com/RIOT-OS/RIOT/actions/runs/6770192155/job/18398079073#step:15:56)

08-interop: Fix contiki script for workflow

---

conftest.py

Does what https://github.com/RIOT-OS/RIOT/pull/20215 did to the release tests.

conftest: use "native" RIOT_TERMINAL for native boards

---

testutils/github.py

The `login_or_token` parameter of the Github class [is deprecated](https://pygithub.readthedocs.io/en/stable/github.html#github.MainClass.Github). See also [here](https://github.com/RIOT-OS/RIOT/actions/runs/7725056382/job/21058488281#step:15:59). To prevent future surprises, let's port over to the recommended alternative, before it gets dropped.

testutils: Avoid deprecated parameter

---

conftest.py

Due to some issues with other border routers running we should harden the tests against that by using a random PAN_ID.
See https://github.com/RIOT-OS/Release-Specs/pull/299 for some info (it contains a train of references)

conftest: Randomize default PAN_ID

---

requirements.txt

The step to paho 2.0.0 [killed our release tests](https://github.com/RIOT-OS/RIOT/actions/runs/7938879612/job/21678272017). This fixes the tests for now, until the `ttn` module is adopted for the new paho API.

requirements.txt: pin paho to <2.0.0

---

testutils/tests/test_github.py

this should fix the CI failure for #308, too

testutils: fix use-yield-from for pylint

---

09-coap/test_spec09.py

adapts the test to the changes from https://github.com/RIOT-OS/RIOT/pull/20554

09-coap: pass URI instead of separate host and path components

---

01-ci/README.md

Nobody actually runs the `compile_test.py` script I hope...

01-ci: Update task 1 compile test

---

04-single-hop-6lowpan-icmp/test_spec04.py
05-single-hop-route/test_spec05.py
08-interop/README.md
08-interop/test_spec08.py
09-coap/test_spec09.py
10-icmpv6-error/README.md
10-icmpv6-error/test_spec10.py
11-lorawan/README.md
11-lorawan/test_spec11.py
testutils/shell.py

As follow-up of https://github.com/RIOT-OS/RIOT/pull/21135 and https://github.com/RIOT-OS/RIOT/pull/21221
(Note that any workflow is expected to fail until the latter PR is merged)

treewide: update links to RIOT examples

---

08-interop/test_spec08.py

Follow-up of #319. While the contiki example is indeed still called `examples/hello-world`, the test uses the RIOT build system to flash it on the board. We thus need to specify an existing RIOT application folder for flashing.

08-interop: use existing RIOT example folder for flashing

---

09-coap/task04.py
09-coap/test_spec09.py

follow-up after https://github.com/RIOT-OS/RIOT/pull/21242 where native was changed to be an alias for native32/64 depending on the host architecture

09-coap: do not expect a specific board name
