RIOT-OS/Release-Specs

- 05-single-hop-route/05-single-hop-route.md
I think that this is copy-pasta, since the other [6Lo task](https://github.com/RIOT-OS/Release-Specs/blob/master/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md) asks for <10% success rate. Additionally, having always a success rate of <1% in a crowded network with 100 1kB packets (which means at least 11 fragments) seems highly unlikely.
> Task 5.2: Results are very tight margin

- 01-ci/01-ci.md
- 02-tests/02-tests.md
- 03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md
- 04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md
- 05-single-hop-route/05-single-hop-route.md
- 06-single-hop-udp/06-single-hop-udp.md
- 07-multi-hop/07-multi-hop.md
- 08-interop/08-interop.md
Add some descriptions to the tasks titles.
Right now when following the Release Specs, there is not description for sub tasks.
I tried explaining what each task is about.
It ended up being a bit long, so I would love if you have suggestions (you can even push directly here).
To be handled it will require a new version of the release manager:
https://github.com/RIOT-OS/RIOT-release-manager/pull/3
The result for the issue generated for the first version of the PR:
https://github.com/cladmi/Release-Specs/issues/1
I tested that all links where going to the right place.
> Add description for tasks

- 08-interop/08-interop.md
See https://github.com/RIOT-OS/Release-Specs/issues/69#issuecomment-411447338
> task8.4: document requirement for SLAAC

- 08-interop/08-interop.md
Forgot to remove those in #72.
> task08: remove outdated remark in lwIP titles

- 07-multi-hop/example_test_guide.md
This commit helps clarify individual steps to take to run the test.
It adds documentation on how to use the shell commands.
> 07-multi-hop: Add detailed documentation

- 11-lorawan/11-lorawan.md
Add release specs for the LoRaWAN features. It would be great to have them for testing the 2019.01 RC3.
> 11-lorawan: add release specs for lorawan

- 07-multi-hop/example_test_guide.md
Getting the packet loss rate of a single packet is not that practical ;-).
> task07: fix UDP packet number

- 10-icmpv6-error/10-icmpv6-error.md
While browsing through the tests to do, I noticed that the stated goal of task 10 was completely wrong (probably copypasta from somewhere else).
> task10: fix stated goal

- 02-tests/02-tests.md
> task02: Fix rebase error of #130

- 02-tests/02-tests.md
Change directory of compile_and_test_for_board.py to proper path
Change directory of tapsetup to proper path
> spec/03: Update directories for scripts

- 08-interop/08-interop.md
This adds a new task to the interop specifications, where UDP packets should be exchanged between a RIOT node and a Zephyr node. The task is similar to what we have with Contiki in task 03. As setup is not so hard and the example works out of the box I though it may be good to add this OS to our testings.
I included detailed instructions on how to setup everything and get it to run.
> 08-Interop: Add task to exchange UDP packets with a Zephyr node

- 08-interop/08-interop.md
https://github.com/RIOT-OS/RIOT/pull/13568 adds another step to the testing procedures of Task 8.3.
> task8.3: adapt testing procedures for current RIOT

- .github/workflows/self-test.yml
Forgot to remove something from the Github Workflow ^^"
> gh-actions: remove test branch from self-test

- README.md
This adds some documentation on how to run specific tasks with the test framework.
> README.md: add note how to run specific tests

- README.md
- requirements.txt
- tox.ini
This PR does two things:
- add doc for local setup
- use `requirements.txt` for dependencies list.
> README: some improvements

- 07-multi-hop/test_spec07.py
While squashing #158 I noticed some potential for clean-up, but sadly it was merged before my test runs finished. So this is a follow-up on that.
> 07-multi-hop: some clean-up for the automated tests

- 09-coap/test_spec09.py
Apparently, just killing the aiocoap server is not such a good idea ;-). With this fix all CoAP tests succeed.
Currently when run completely spec09 is failing on the last task
```sh
sudo RIOTBASE=$(readlink -f ../RIOT) tox -e test -- -k "spec09" --non-RC
```
the reason is because both task02 and task09 start a CoAP server. This can be shown by just running those tasks (for task02 only the version that starts the server)
```sh
sudo RIOTBASE=$(readlink -f ../RIOT) tox -e test -- -k "spec09 and ((task02 and True) or task05)" --non-RC
```
On current master this is broken, with this PR all tasks will succeed again.
> 09-coap/task02&05: shutdown server properly

- tox.ini
See https://github.com/RIOT-OS/RIOT/pull/14646#pullrequestreview-461640916.
> tox: remove unneeded gh-actions env

- 04-single-hop-6lowpan-icmp/test_spec04.py
Task 4.4 fails on the CI, since the Github servers appear to silently drop the TCP connection to the node after a while (the pinged node is not accessed for the duration of the ping). By just starting the terminal anew, this is fixed. I will start a new run, once I merged this PR into #174.
This requires https://github.com/RIOT-OS/riotctrl/pull/6 to work.
> 04-single-hop-6lowpan-icmp/task04: reconnect terminal after long test

- 09-coap/test_spec09.py
This PR replaces the implementation of Cord EP ShellInteraction here with upstream as requested https://github.com/RIOT-OS/RIOT/pull/14715#issuecomment-669884370.
```bash
sudo RIOTBASE=$(readlink -f ../RIOT) tox -e test -- -k "spec09 and task01" --non-RC
```
> 09-coap/task01: use upstream CordEp ShellInteraction

- README.md
This PR adds a README entry for the requirements and setup steps for TTN.
> README.md: add TTN requirements

- 08-interop/README.md
Tasks 8.12 and 8.13 do not have very descriptive titles. This changes that.
> 08-interop: more descriptive titles for tasks 12 & 13

- 03-single-hop-ipv6-icmp/test_spec03.py
- 07-multi-hop/test_spec07.py
- 08-interop/test_spec08.py
- 09-coap/task03.py
- 09-coap/task04.py
- 09-coap/task05.py
- 09-coap/test_spec09.py
- conftest.py
- setup.cfg
- testutils/git.py
- testutils/github.py
- testutils/iotlab.py
- testutils/pytest.py
- testutils/shell.py
- testutils/tests/test_github.py
- testutils/tests/test_ttn.py
- testutils/ttn.py
This used https://github.com/ikamensh/flynt to convert possible cases to f-strings. No manual replacement was performed.
> treewide: use f-string where possible

- .github/workflows/self-test.yml
Updates the GitHub action to also test for python 3.10.
> self-test: test for python 3.10

- 04-single-hop-6lowpan-icmp/example_test_guide.md
- 07-multi-hop/example_test_guide.md
- 08-interop/README.md
Just instruct users to use the `ping` command instead.
> replace ping6 with ping in doc

- 08-interop/README.md
There is no Linux involved here (unless you count the remote server and your home router).
> 08-interop: fix naming of task #13

- README.md
> README.md: Fix broken link

- testutils/github.py
- testutils/tests/test_github.py
CI seems to be failing.  Simple fix to correct it!
> testutils: Fix black style

- testutils/pytest.py
> testutils/pytest.py: fix format string and hint to connect once manually
